### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by mihailtd** [jayZOU/vue-schedule#4]
Hello, 
Love the component!
However I am having trouble getting it to work properly.
When I import it into my app, I get this error: `Uncaught SyntaxError: Unexpected token import`.
I am using it in a [vuejs webpack starter app](http://vuejs-templates.github.io/webpack/), so I would think it's because of webpack...
I am using:
* VueJS v.2.4.2
* Babel v6.0.0
* and Webpack 1.15.0

I donțt know what other info I could give since the error is so generic.
Any ideeas why this is happening? Any suggestions? 
Thank you very much!

**Comment by matthecarl** [comment]
@farcasmihai91 The following may help https://github.com/webpack/webpack/issues/4857

**Comment by mihailtd** [comment]
Upgraded project to:
* "vue": "^2.5.2"
* "babel-core": "^6.22.1"
* "webpack": "^3.6.0"

All works great!
I don't know what the issue was, but definitely not with this component.

Thanks!
